### PR TITLE
chore: upgrade cozy-client-js and other libs

### PR DESCRIPTION
**Pull request by doubleface**
This will fix security alerts.

I found no regression with my use of ACH. It would be nice if someone could test it before I merge it.

### CODE REVIEW

**Comment by ptbrowne** [comment]
To test:

```
mkdir test
cd test
yarn init
yarn add ach@https://github.com/cozy/ach.git#chore/upgradeLibs`
```

I had to install babel-runtime since it is configured as peer dependency. In a separate PR I will remove it, we should not rely on it on node.
I tested an export and it worked. The build is red though.

**Comment by doubleface** [comment]
@ptbrowne I see, I have babel-runtime installed because it comes from devDependencies (jest). I will add it as a dependency.

**Comment by cedricmessiant** [comment]
LGTM. I tested export and import of contacts, everything is fine. I would like to test the migrateContacts script but I have to rebase master first

**Comment by ptbrowne** [comment]
:shipit:

**Pull request merged**
