### PR TITLE
Refactor in order to replace commander

### PR DESCRIPTION
**Pull request by ptbrowne**
The idea is to refactor a bit the code to 

- Separate commander specific idioms (reliance on program global,
difference between arguments and options) from the main code.

I would like in further PRs to completely remove commander and
use argparse as I find it more suitable to build `git-like`
CLI programs with "modes".

Here, even if we do not fully remove commander, I think the code
is in a better state than before.

### CODE REVIEW

**Comment by ptbrowne** [comment]
If we add unit-tests, they would test only the interface between our command handlers and argparse, merely checking that we do not do anything wrong ?

I think the most suitable would be to have an e2e test with several commands :

```
ach import file.json
ach downloadFile
expect("file.pdf").toExist()
ach export io.cozy.bills > output.json
expect("output.json").toContain("io.cozy.bills")
```

For this we should be able to create a throwaway Cozy easily.

**Comment by nono** [comment]
Can we merge this PR?

**Comment by ptbrowne** [comment]
Thanks nono. Yannick I created an issue to run the E2E test on the CI : https://github.com/cozy/ACH/issues/65

**Pull request merged**
